# Project Name
TARGET = daisyCppTest2

# Sources
CPP_SOURCES = daisyTest2.cpp

# Library Locations
ROOT_DIR = ../libs
LIBDAISY_DIR = $(ROOT_DIR)/libdaisy
DAISYSP_DIR = $(ROOT_DIR)/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

