# Project Name
TARGET = daisyFirstCppTest

# Sources
CPP_SOURCES = main.cpp

# Library Locations
MAIN_LOCATION = C:/Users/VIDIIANsystems/Documents/Electro-Smith/DaisyExamples

LIBDAISY_DIR = $(MAIN_LOCATION)/libdaisy
DAISYSP_DIR = $(MAIN_LOCATION)/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

