# Project Name
TARGET = ex_patch_pluck_echo

# Sources
CPP_SOURCES = PodMidi.cpp

# Library Locations
ROOT = ../libs
LIBDAISY_DIR = $(ROOT)/libdaisy
DAISYSP_DIR = $(ROOT)/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

